//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TICPivotalQAController {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControllerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControllerResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TICPivotalQAController.ControllerResource", typeof(ControllerResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecordId is empty.
        /// </summary>
        internal static string MSG_EMPTY_RECORDID {
            get {
                return ResourceManager.GetString("MSG_EMPTY_RECORDID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System name is empty.
        /// </summary>
        internal static string MSG_EMPTY_SYSTEM_NAME {
            get {
                return ResourceManager.GetString("MSG_EMPTY_SYSTEM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in reading WebSvcConfiguration.xml path.This could be for the following reasons:1) Check whether the Web.Config exists in the project directory.2) ConfigFilePath custom element is missing.3) ConfigFilePath is not set properly to the file path..
        /// </summary>
        internal static string MSG_FAILED_TO_READ_CONFIG_FILE {
            get {
                return ResourceManager.GetString("MSG_FAILED_TO_READ_CONFIG_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields and Operators do not match.
        /// </summary>
        internal static string MSG_FIELDS_OPERATORS_DONOT_MATCH {
            get {
                return ResourceManager.GetString("MSG_FIELDS_OPERATORS_DONOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WebSvcConfiguration.xml is invalid.Please check against schema validation.
        /// </summary>
        internal static string MSG_INVALID_CONFIG_FILE {
            get {
                return ResourceManager.GetString("MSG_INVALID_CONFIG_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Value pair mismatch.
        /// </summary>
        internal static string MSG_KEY_VALUE_PAIR_DONOT_MATCH {
            get {
                return ResourceManager.GetString("MSG_KEY_VALUE_PAIR_DONOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is null.
        /// </summary>
        internal static string MSG_NULL {
            get {
                return ResourceManager.GetString("MSG_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys List is Null.
        /// </summary>
        internal static string MSG_NULL_KEYLIST {
            get {
                return ResourceManager.GetString("MSG_NULL_KEYLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operators List is null.
        /// </summary>
        internal static string MSG_NULL_OPERATORSLIST {
            get {
                return ResourceManager.GetString("MSG_NULL_OPERATORSLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values list is null.
        /// </summary>
        internal static string MSG_NULL_VALUESLIST {
            get {
                return ResourceManager.GetString("MSG_NULL_VALUESLIST", resourceCulture);
            }
        }
    }
}
