

/****************************************************************************
 GenericData.cs : File for generic functions by other classes.
 Generated by Pivotal Web Services Generator r5.9.
 Do not modify  the contents of this file with the code editor.
 Copyright (c) 2006, Pivotal Corporation
 ***************************************************************************/
using System;
using System.Resources;
using System.Globalization;




namespace TICQAPBSComms
{
    public class GenericData
    {
        public GenericData()
        {
            System.Threading.Thread.CurrentThread.CurrentUICulture = CultureInfo.InstalledUICulture;
            resMan = new ResourceManager("TICPivotalQAPivotalGlobal.Resource", GetType().Assembly);
        }


        #region Accessor Functions

        /// <summary>
        /// Returns string from the resource file based on the key.
        /// </summary>
        /// <returns>Resource string </returns>
        public string GetString(string key)
        {
            return resMan.GetString(key);
        }

        #endregion

        #region private members

        private ResourceManager resMan;

        #endregion
    }

}