//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 

namespace CdcSoftware.Pivotal.Applications.HomeBuilders.EF.Server.EnvisionXsdGenerated
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Builder
    {

        private OrganizationType organizationField;

        private string nameField;

        private System.DateTime dateGeneratedField;

        private string nHTNumberField;

        /// <remarks/>
        public OrganizationType Organization
        {
            get
            {
                return this.organizationField;
            }
            set
            {
                this.organizationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateGenerated
        {
            get
            {
                return this.dateGeneratedField;
            }
            set
            {
                this.dateGeneratedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NHTNumber
        {
            get
            {
                return this.nHTNumberField;
            }
            set
            {
                this.nHTNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OrganizationType
    {

        private DesignOptionType[] organizationOptionsField;

        private OrganizationType[] organizationField;

        private OrganizationTypeInventory[] inventoryField;

        private string nameField;

        private string locationNumberField;

        private string locationLevelField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Option", IsNullable = false)]
        public DesignOptionType[] OrganizationOptions
        {
            get
            {
                return this.organizationOptionsField;
            }
            set
            {
                this.organizationOptionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Organization")]
        public OrganizationType[] Organization
        {
            get
            {
                return this.organizationField;
            }
            set
            {
                this.organizationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Inventory")]
        public OrganizationTypeInventory[] Inventory
        {
            get
            {
                return this.inventoryField;
            }
            set
            {
                this.inventoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LocationNumber
        {
            get
            {
                return this.locationNumberField;
            }
            set
            {
                this.locationNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LocationLevel
        {
            get
            {
                return this.locationLevelField;
            }
            set
            {
                this.locationLevelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DesignOptionType
    {

        private DesignOptionTypeIncludedOption[] packageField;

        private object optionNameField;

        private object optionDescriptionField;

        private OptionImageType[] imagesField;

        private DesignOptionTypeProduct[] productsField;

        private DesignOptionTypeRule[] rulesField;

        private string optionNumberField;

        private DesignOptionTypeOptionType optionTypeField;

        private bool optionTypeFieldSpecified;

        private string categoryNumberField;

        private string cutoffStageNumberField;

        private decimal priceField;

        private decimal postCutoffPriceField;

        private bool postCutoffPriceFieldSpecified;

        private bool structuralField;

        private bool suppressPriceField;

        private bool suppressDisplayField;

        private bool deactivateField;

        private System.DateTime validFromField;

        private bool validFromFieldSpecified;

        private System.DateTime validToField;

        private bool validToFieldSpecified;

        public DesignOptionType()
        {
            this.structuralField = false;
            this.suppressPriceField = false;
            this.suppressDisplayField = false;
            this.deactivateField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("IncludedOption", IsNullable = false)]
        public DesignOptionTypeIncludedOption[] Package
        {
            get
            {
                return this.packageField;
            }
            set
            {
                this.packageField = value;
            }
        }

        /// <remarks/>
        public object OptionName
        {
            get
            {
                return this.optionNameField;
            }
            set
            {
                this.optionNameField = value;
            }
        }

        /// <remarks/>
        public object OptionDescription
        {
            get
            {
                return this.optionDescriptionField;
            }
            set
            {
                this.optionDescriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Image", IsNullable = false)]
        public OptionImageType[] Images
        {
            get
            {
                return this.imagesField;
            }
            set
            {
                this.imagesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Product", IsNullable = false)]
        public DesignOptionTypeProduct[] Products
        {
            get
            {
                return this.productsField;
            }
            set
            {
                this.productsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Rule", IsNullable = false)]
        public DesignOptionTypeRule[] Rules
        {
            get
            {
                return this.rulesField;
            }
            set
            {
                this.rulesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OptionNumber
        {
            get
            {
                return this.optionNumberField;
            }
            set
            {
                this.optionNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DesignOptionTypeOptionType OptionType
        {
            get
            {
                return this.optionTypeField;
            }
            set
            {
                this.optionTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OptionTypeSpecified
        {
            get
            {
                return this.optionTypeFieldSpecified;
            }
            set
            {
                this.optionTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CategoryNumber
        {
            get
            {
                return this.categoryNumberField;
            }
            set
            {
                this.categoryNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CutoffStageNumber
        {
            get
            {
                return this.cutoffStageNumberField;
            }
            set
            {
                this.cutoffStageNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PostCutoffPrice
        {
            get
            {
                return this.postCutoffPriceField;
            }
            set
            {
                this.postCutoffPriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PostCutoffPriceSpecified
        {
            get
            {
                return this.postCutoffPriceFieldSpecified;
            }
            set
            {
                this.postCutoffPriceFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Structural
        {
            get
            {
                return this.structuralField;
            }
            set
            {
                this.structuralField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool SuppressPrice
        {
            get
            {
                return this.suppressPriceField;
            }
            set
            {
                this.suppressPriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool SuppressDisplay
        {
            get
            {
                return this.suppressDisplayField;
            }
            set
            {
                this.suppressDisplayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Deactivate
        {
            get
            {
                return this.deactivateField;
            }
            set
            {
                this.deactivateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime ValidFrom
        {
            get
            {
                return this.validFromField;
            }
            set
            {
                this.validFromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidFromSpecified
        {
            get
            {
                return this.validFromFieldSpecified;
            }
            set
            {
                this.validFromFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime ValidTo
        {
            get
            {
                return this.validToField;
            }
            set
            {
                this.validToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidToSpecified
        {
            get
            {
                return this.validToFieldSpecified;
            }
            set
            {
                this.validToFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DesignOptionTypeIncludedOption
    {

        private string optionNumberField;

        private string locationNumberField;

        private string locationLevelField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OptionNumber
        {
            get
            {
                return this.optionNumberField;
            }
            set
            {
                this.optionNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LocationNumber
        {
            get
            {
                return this.locationNumberField;
            }
            set
            {
                this.locationNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LocationLevel
        {
            get
            {
                return this.locationLevelField;
            }
            set
            {
                this.locationLevelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IntersectionOptionType
    {

        private string optionNumberField;

        private string locationNumberField;

        private string locationLevelField;

        private string roomNumberField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OptionNumber
        {
            get
            {
                return this.optionNumberField;
            }
            set
            {
                this.optionNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LocationNumber
        {
            get
            {
                return this.locationNumberField;
            }
            set
            {
                this.locationNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LocationLevel
        {
            get
            {
                return this.locationLevelField;
            }
            set
            {
                this.locationLevelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RoomNumber
        {
            get
            {
                return this.roomNumberField;
            }
            set
            {
                this.roomNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OptionImageType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImageType
    {

        private string sequencePositionField;

        private string captionField;

        private ImageReferenceType referenceTypeField;

        private bool referenceTypeFieldSpecified;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
        public string SequencePosition
        {
            get
            {
                return this.sequencePositionField;
            }
            set
            {
                this.sequencePositionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Caption
        {
            get
            {
                return this.captionField;
            }
            set
            {
                this.captionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ImageReferenceType ReferenceType
        {
            get
            {
                return this.referenceTypeField;
            }
            set
            {
                this.referenceTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReferenceTypeSpecified
        {
            get
            {
                return this.referenceTypeFieldSpecified;
            }
            set
            {
                this.referenceTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    public enum ImageReferenceType
    {

        /// <remarks/>
        Filename,

        /// <remarks/>
        URL,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OptionImageType : ImageType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InventoryType
    {

        private InventoryTypeInventoryImage[] inventoryImagesField;

        private DesignOptionType[] inventoryOptionsField;

        private OptionAssignmentType[] assignmentsField;

        private RoomType[] roomsField;

        private InventoryType[] inventoryField;

        private InventoryTypeIntersectionRule[] intersectionRulesField;

        private string nameField;

        private string locationNumberField;

        private string locationLevelField;

        private bool deactivateField;

        private string integrationKeyField;

        private bool suppressEDCPresaleWishlistField;

        private bool suppressEDCOptionCompareField;

        private bool suppressEDCConfirmedTotalField;

        public InventoryType()
        {
            this.deactivateField = false;
            this.suppressEDCPresaleWishlistField = false;
            this.suppressEDCOptionCompareField = false;
            this.suppressEDCConfirmedTotalField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("InventoryImage", IsNullable = false)]
        public InventoryTypeInventoryImage[] InventoryImages
        {
            get
            {
                return this.inventoryImagesField;
            }
            set
            {
                this.inventoryImagesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Option", IsNullable = false)]
        public DesignOptionType[] InventoryOptions
        {
            get
            {
                return this.inventoryOptionsField;
            }
            set
            {
                this.inventoryOptionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Assignment", IsNullable = false)]
        public OptionAssignmentType[] Assignments
        {
            get
            {
                return this.assignmentsField;
            }
            set
            {
                this.assignmentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Room", IsNullable = false)]
        public RoomType[] Rooms
        {
            get
            {
                return this.roomsField;
            }
            set
            {
                this.roomsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Inventory")]
        public InventoryType[] Inventory
        {
            get
            {
                return this.inventoryField;
            }
            set
            {
                this.inventoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("IntersectionRule", IsNullable = false)]
        public InventoryTypeIntersectionRule[] IntersectionRules
        {
            get
            {
                return this.intersectionRulesField;
            }
            set
            {
                this.intersectionRulesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LocationNumber
        {
            get
            {
                return this.locationNumberField;
            }
            set
            {
                this.locationNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LocationLevel
        {
            get
            {
                return this.locationLevelField;
            }
            set
            {
                this.locationLevelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Deactivate
        {
            get
            {
                return this.deactivateField;
            }
            set
            {
                this.deactivateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IntegrationKey
        {
            get
            {
                return this.integrationKeyField;
            }
            set
            {
                this.integrationKeyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool SuppressEDCPresaleWishlist
        {
            get
            {
                return this.suppressEDCPresaleWishlistField;
            }
            set
            {
                this.suppressEDCPresaleWishlistField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool SuppressEDCOptionCompare
        {
            get
            {
                return this.suppressEDCOptionCompareField;
            }
            set
            {
                this.suppressEDCOptionCompareField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool SuppressEDCConfirmedTotal
        {
            get
            {
                return this.suppressEDCConfirmedTotalField;
            }
            set
            {
                this.suppressEDCConfirmedTotalField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class InventoryTypeInventoryImage : ImageType
    {

        private InventoryTypeInventoryImageImageType imageType1Field;

        private bool imageType1FieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("ImageType")]
        public InventoryTypeInventoryImageImageType ImageType1
        {
            get
            {
                return this.imageType1Field;
            }
            set
            {
                this.imageType1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ImageType1Specified
        {
            get
            {
                return this.imageType1FieldSpecified;
            }
            set
            {
                this.imageType1FieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum InventoryTypeInventoryImageImageType
    {

        /// <remarks/>
        FloorPlan,

        /// <remarks/>
        Elevation,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OptionAssignmentType
    {

        private string optionNumberField;

        private string locationNumberField;

        private string locationLevelField;

        private string cutoffStageNumberField;

        private decimal priceField;

        private decimal postCutoffPriceField;

        private bool postCutoffPriceFieldSpecified;

        private bool standardField;

        private bool deactivateField;

        private bool financeableField;

        public OptionAssignmentType()
        {
            this.standardField = false;
            this.deactivateField = false;
            this.financeableField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OptionNumber
        {
            get
            {
                return this.optionNumberField;
            }
            set
            {
                this.optionNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LocationNumber
        {
            get
            {
                return this.locationNumberField;
            }
            set
            {
                this.locationNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LocationLevel
        {
            get
            {
                return this.locationLevelField;
            }
            set
            {
                this.locationLevelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CutoffStageNumber
        {
            get
            {
                return this.cutoffStageNumberField;
            }
            set
            {
                this.cutoffStageNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PostCutoffPrice
        {
            get
            {
                return this.postCutoffPriceField;
            }
            set
            {
                this.postCutoffPriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PostCutoffPriceSpecified
        {
            get
            {
                return this.postCutoffPriceFieldSpecified;
            }
            set
            {
                this.postCutoffPriceFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Standard
        {
            get
            {
                return this.standardField;
            }
            set
            {
                this.standardField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Deactivate
        {
            get
            {
                return this.deactivateField;
            }
            set
            {
                this.deactivateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Financeable
        {
            get
            {
                return this.financeableField;
            }
            set
            {
                this.financeableField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RoomType
    {

        private OptionAssignmentType[] roomAssignmentField;

        private string nameField;

        private string roomNumberField;

        private RoomTypeRoomType roomType1Field;

        private bool deactivateField;

        public RoomType()
        {
            this.deactivateField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RoomAssignment")]
        public OptionAssignmentType[] RoomAssignment
        {
            get
            {
                return this.roomAssignmentField;
            }
            set
            {
                this.roomAssignmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RoomNumber
        {
            get
            {
                return this.roomNumberField;
            }
            set
            {
                this.roomNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("RoomType")]
        public RoomTypeRoomType RoomType1
        {
            get
            {
                return this.roomType1Field;
            }
            set
            {
                this.roomType1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Deactivate
        {
            get
            {
                return this.deactivateField;
            }
            set
            {
                this.deactivateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum RoomTypeRoomType
    {

        /// <remarks/>
        Kitchen,

        /// <remarks/>
        MasterBedroom,

        /// <remarks/>
        Bedroom,

        /// <remarks/>
        MasterBathroom,

        /// <remarks/>
        Bathroom,

        /// <remarks/>
        LivingArea,

        /// <remarks/>
        Garage,

        /// <remarks/>
        InteriorGeneral,

        /// <remarks/>
        ExteriorGeneral,

        /// <remarks/>
        Basement,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class InventoryTypeIntersectionRule
    {

        private IntersectionOptionType[] prerequisiteOptionsField;

        private IntersectionOptionType[] postrequisiteOptionsField;

        private string intersectionRuleNumberField;

        private string deactivateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PrerequisiteOption", IsNullable = false)]
        public IntersectionOptionType[] PrerequisiteOptions
        {
            get
            {
                return this.prerequisiteOptionsField;
            }
            set
            {
                this.prerequisiteOptionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PostrequisiteOption", IsNullable = false)]
        public IntersectionOptionType[] PostrequisiteOptions
        {
            get
            {
                return this.postrequisiteOptionsField;
            }
            set
            {
                this.postrequisiteOptionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IntersectionRuleNumber
        {
            get
            {
                return this.intersectionRuleNumberField;
            }
            set
            {
                this.intersectionRuleNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Deactivate
        {
            get
            {
                return this.deactivateField;
            }
            set
            {
                this.deactivateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DesignOptionTypeProduct
    {

        private string gTINField;

        private string nHTManufacturerNumberField;

        private string productNumberField;

        private string dUNSNumberField;

        private string uCCCodeField;

        private bool isPrimaryField;

        public DesignOptionTypeProduct()
        {
            this.isPrimaryField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string GTIN
        {
            get
            {
                return this.gTINField;
            }
            set
            {
                this.gTINField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NHTManufacturerNumber
        {
            get
            {
                return this.nHTManufacturerNumberField;
            }
            set
            {
                this.nHTManufacturerNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProductNumber
        {
            get
            {
                return this.productNumberField;
            }
            set
            {
                this.productNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DUNSNumber
        {
            get
            {
                return this.dUNSNumberField;
            }
            set
            {
                this.dUNSNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UCCCode
        {
            get
            {
                return this.uCCCodeField;
            }
            set
            {
                this.uCCCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsPrimary
        {
            get
            {
                return this.isPrimaryField;
            }
            set
            {
                this.isPrimaryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DesignOptionTypeRule
    {

        private DesignOptionTypeRuleRuleType ruleTypeField;

        private bool ruleTypeFieldSpecified;

        private string optionNumberField;

        private string locationNumberField;

        private string locationLevelField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DesignOptionTypeRuleRuleType RuleType
        {
            get
            {
                return this.ruleTypeField;
            }
            set
            {
                this.ruleTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RuleTypeSpecified
        {
            get
            {
                return this.ruleTypeFieldSpecified;
            }
            set
            {
                this.ruleTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OptionNumber
        {
            get
            {
                return this.optionNumberField;
            }
            set
            {
                this.optionNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LocationNumber
        {
            get
            {
                return this.locationNumberField;
            }
            set
            {
                this.locationNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LocationLevel
        {
            get
            {
                return this.locationLevelField;
            }
            set
            {
                this.locationLevelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum DesignOptionTypeRuleRuleType
    {

        /// <remarks/>
        Enables,

        /// <remarks/>
        Excludes,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum DesignOptionTypeOptionType
    {

        /// <remarks/>
        Normal,

        /// <remarks/>
        Group,

        /// <remarks/>
        Package,

        /// <remarks/>
        Feature,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OrganizationTypeInventory : InventoryType
    {
    }
}