//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3615.
// 
#pragma warning disable 1591

namespace WebServiceTester.QAServiceTest {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TICPivotalQAServiceSvcSoap", Namespace="http://tempuri.org/TICPivotalQAService")]
    public partial class TICPivotalQAServiceSvc : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AuthenticateUserLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPivotalMD5MessageDigestOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetScheduledInspectionsForUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInspectionsForUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateNewInspectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApplyInspectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestDALOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TICPivotalQAServiceSvc() {
            this.Url = global::WebServiceTester.Properties.Settings.Default.WebServiceTester_QAServiceTest_TICPivotalQAServiceSvc;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AuthenticateUserLoginCompletedEventHandler AuthenticateUserLoginCompleted;
        
        /// <remarks/>
        public event GetPivotalMD5MessageDigestCompletedEventHandler GetPivotalMD5MessageDigestCompleted;
        
        /// <remarks/>
        public event GetScheduledInspectionsForUserCompletedEventHandler GetScheduledInspectionsForUserCompleted;
        
        /// <remarks/>
        public event GetInspectionsForUserCompletedEventHandler GetInspectionsForUserCompleted;
        
        /// <remarks/>
        public event CreateNewInspectionCompletedEventHandler CreateNewInspectionCompleted;
        
        /// <remarks/>
        public event ApplyInspectionCompletedEventHandler ApplyInspectionCompleted;
        
        /// <remarks/>
        public event TestDALCompletedEventHandler TestDALCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TICPivotalQAService/AuthenticateUserLogin", RequestNamespace="http://tempuri.org/TICPivotalQAService", ResponseNamespace="http://tempuri.org/TICPivotalQAService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InspectorObj AuthenticateUserLogin(string userName, string passwordHash) {
            object[] results = this.Invoke("AuthenticateUserLogin", new object[] {
                        userName,
                        passwordHash});
            return ((InspectorObj)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateUserLoginAsync(string userName, string passwordHash) {
            this.AuthenticateUserLoginAsync(userName, passwordHash, null);
        }
        
        /// <remarks/>
        public void AuthenticateUserLoginAsync(string userName, string passwordHash, object userState) {
            if ((this.AuthenticateUserLoginOperationCompleted == null)) {
                this.AuthenticateUserLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateUserLoginOperationCompleted);
            }
            this.InvokeAsync("AuthenticateUserLogin", new object[] {
                        userName,
                        passwordHash}, this.AuthenticateUserLoginOperationCompleted, userState);
        }
        
        private void OnAuthenticateUserLoginOperationCompleted(object arg) {
            if ((this.AuthenticateUserLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateUserLoginCompleted(this, new AuthenticateUserLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TICPivotalQAService/GetPivotalMD5MessageDigest", RequestNamespace="http://tempuri.org/TICPivotalQAService", ResponseNamespace="http://tempuri.org/TICPivotalQAService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPivotalMD5MessageDigest(string plainTextPassword) {
            object[] results = this.Invoke("GetPivotalMD5MessageDigest", new object[] {
                        plainTextPassword});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPivotalMD5MessageDigestAsync(string plainTextPassword) {
            this.GetPivotalMD5MessageDigestAsync(plainTextPassword, null);
        }
        
        /// <remarks/>
        public void GetPivotalMD5MessageDigestAsync(string plainTextPassword, object userState) {
            if ((this.GetPivotalMD5MessageDigestOperationCompleted == null)) {
                this.GetPivotalMD5MessageDigestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPivotalMD5MessageDigestOperationCompleted);
            }
            this.InvokeAsync("GetPivotalMD5MessageDigest", new object[] {
                        plainTextPassword}, this.GetPivotalMD5MessageDigestOperationCompleted, userState);
        }
        
        private void OnGetPivotalMD5MessageDigestOperationCompleted(object arg) {
            if ((this.GetPivotalMD5MessageDigestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPivotalMD5MessageDigestCompleted(this, new GetPivotalMD5MessageDigestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TICPivotalQAService/GetScheduledInspectionsForUser", RequestNamespace="http://tempuri.org/TICPivotalQAService", ResponseNamespace="http://tempuri.org/TICPivotalQAService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ScheduledInspectionWrapper GetScheduledInspectionsForUser(string userLogin) {
            object[] results = this.Invoke("GetScheduledInspectionsForUser", new object[] {
                        userLogin});
            return ((ScheduledInspectionWrapper)(results[0]));
        }
        
        /// <remarks/>
        public void GetScheduledInspectionsForUserAsync(string userLogin) {
            this.GetScheduledInspectionsForUserAsync(userLogin, null);
        }
        
        /// <remarks/>
        public void GetScheduledInspectionsForUserAsync(string userLogin, object userState) {
            if ((this.GetScheduledInspectionsForUserOperationCompleted == null)) {
                this.GetScheduledInspectionsForUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetScheduledInspectionsForUserOperationCompleted);
            }
            this.InvokeAsync("GetScheduledInspectionsForUser", new object[] {
                        userLogin}, this.GetScheduledInspectionsForUserOperationCompleted, userState);
        }
        
        private void OnGetScheduledInspectionsForUserOperationCompleted(object arg) {
            if ((this.GetScheduledInspectionsForUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetScheduledInspectionsForUserCompleted(this, new GetScheduledInspectionsForUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TICPivotalQAService/GetInspectionsForUser", RequestNamespace="http://tempuri.org/TICPivotalQAService", ResponseNamespace="http://tempuri.org/TICPivotalQAService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InspectionWrapper GetInspectionsForUser(string userLogin) {
            object[] results = this.Invoke("GetInspectionsForUser", new object[] {
                        userLogin});
            return ((InspectionWrapper)(results[0]));
        }
        
        /// <remarks/>
        public void GetInspectionsForUserAsync(string userLogin) {
            this.GetInspectionsForUserAsync(userLogin, null);
        }
        
        /// <remarks/>
        public void GetInspectionsForUserAsync(string userLogin, object userState) {
            if ((this.GetInspectionsForUserOperationCompleted == null)) {
                this.GetInspectionsForUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInspectionsForUserOperationCompleted);
            }
            this.InvokeAsync("GetInspectionsForUser", new object[] {
                        userLogin}, this.GetInspectionsForUserOperationCompleted, userState);
        }
        
        private void OnGetInspectionsForUserOperationCompleted(object arg) {
            if ((this.GetInspectionsForUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInspectionsForUserCompleted(this, new GetInspectionsForUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TICPivotalQAService/CreateNewInspection", RequestNamespace="http://tempuri.org/TICPivotalQAService", ResponseNamespace="http://tempuri.org/TICPivotalQAService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InspectionTemplate CreateNewInspection(string[] scheduledInspectionIds) {
            object[] results = this.Invoke("CreateNewInspection", new object[] {
                        scheduledInspectionIds});
            return ((InspectionTemplate)(results[0]));
        }
        
        /// <remarks/>
        public void CreateNewInspectionAsync(string[] scheduledInspectionIds) {
            this.CreateNewInspectionAsync(scheduledInspectionIds, null);
        }
        
        /// <remarks/>
        public void CreateNewInspectionAsync(string[] scheduledInspectionIds, object userState) {
            if ((this.CreateNewInspectionOperationCompleted == null)) {
                this.CreateNewInspectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateNewInspectionOperationCompleted);
            }
            this.InvokeAsync("CreateNewInspection", new object[] {
                        scheduledInspectionIds}, this.CreateNewInspectionOperationCompleted, userState);
        }
        
        private void OnCreateNewInspectionOperationCompleted(object arg) {
            if ((this.CreateNewInspectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateNewInspectionCompleted(this, new CreateNewInspectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TICPivotalQAService/ApplyInspection", RequestNamespace="http://tempuri.org/TICPivotalQAService", ResponseNamespace="http://tempuri.org/TICPivotalQAService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ApplyInspection(Inspection inspection, ActionForInspection action) {
            this.Invoke("ApplyInspection", new object[] {
                        inspection,
                        action});
        }
        
        /// <remarks/>
        public void ApplyInspectionAsync(Inspection inspection, ActionForInspection action) {
            this.ApplyInspectionAsync(inspection, action, null);
        }
        
        /// <remarks/>
        public void ApplyInspectionAsync(Inspection inspection, ActionForInspection action, object userState) {
            if ((this.ApplyInspectionOperationCompleted == null)) {
                this.ApplyInspectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApplyInspectionOperationCompleted);
            }
            this.InvokeAsync("ApplyInspection", new object[] {
                        inspection,
                        action}, this.ApplyInspectionOperationCompleted, userState);
        }
        
        private void OnApplyInspectionOperationCompleted(object arg) {
            if ((this.ApplyInspectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApplyInspectionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TICPivotalQAService/TestDAL", RequestNamespace="http://tempuri.org/TICPivotalQAService", ResponseNamespace="http://tempuri.org/TICPivotalQAService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InspectorObj TestDAL() {
            object[] results = this.Invoke("TestDAL", new object[0]);
            return ((InspectorObj)(results[0]));
        }
        
        /// <remarks/>
        public void TestDALAsync() {
            this.TestDALAsync(null);
        }
        
        /// <remarks/>
        public void TestDALAsync(object userState) {
            if ((this.TestDALOperationCompleted == null)) {
                this.TestDALOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestDALOperationCompleted);
            }
            this.InvokeAsync("TestDAL", new object[0], this.TestDALOperationCompleted, userState);
        }
        
        private void OnTestDALOperationCompleted(object arg) {
            if ((this.TestDALCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestDALCompleted(this, new TestDALCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/TICPivotalQAService")]
    public partial class InspectorObj {
        
        private string contactHexIdField;
        
        private string typeField;
        
        private string first_NameField;
        
        private string last_NameField;
        
        private string middle_InitialField;
        
        private string titleField;
        
        private string suffixField;
        
        private string company_NameField;
        
        private string emailField;
        
        private InspectorObj[] impersUsersField;
        
        /// <remarks/>
        public string contactHexId {
            get {
                return this.contactHexIdField;
            }
            set {
                this.contactHexIdField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string First_Name {
            get {
                return this.first_NameField;
            }
            set {
                this.first_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Last_Name {
            get {
                return this.last_NameField;
            }
            set {
                this.last_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Middle_Initial {
            get {
                return this.middle_InitialField;
            }
            set {
                this.middle_InitialField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Suffix {
            get {
                return this.suffixField;
            }
            set {
                this.suffixField = value;
            }
        }
        
        /// <remarks/>
        public string Company_Name {
            get {
                return this.company_NameField;
            }
            set {
                this.company_NameField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public InspectorObj[] impersUsers {
            get {
                return this.impersUsersField;
            }
            set {
                this.impersUsersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/TICPivotalQAService")]
    public partial class InspectionTemplate {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/TICPivotalQAService")]
    public partial class Inspection {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/TICPivotalQAService")]
    public partial class InspectionWrapper {
        
        private FilterWrapper filterWrapperField;
        
        private Inspection[] inspectionsField;
        
        /// <remarks/>
        public FilterWrapper filterWrapper {
            get {
                return this.filterWrapperField;
            }
            set {
                this.filterWrapperField = value;
            }
        }
        
        /// <remarks/>
        public Inspection[] inspections {
            get {
                return this.inspectionsField;
            }
            set {
                this.inspectionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/TICPivotalQAService")]
    public partial class FilterWrapper {
        
        private ProjectFilter[] projFilterField;
        
        private PhaseFilter[] phaseFilterField;
        
        private InspectionTypeFilter[] inspectionTypeFilterField;
        
        /// <remarks/>
        public ProjectFilter[] projFilter {
            get {
                return this.projFilterField;
            }
            set {
                this.projFilterField = value;
            }
        }
        
        /// <remarks/>
        public PhaseFilter[] phaseFilter {
            get {
                return this.phaseFilterField;
            }
            set {
                this.phaseFilterField = value;
            }
        }
        
        /// <remarks/>
        public InspectionTypeFilter[] inspectionTypeFilter {
            get {
                return this.inspectionTypeFilterField;
            }
            set {
                this.inspectionTypeFilterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/TICPivotalQAService")]
    public partial class ProjectFilter {
        
        private string projectIdField;
        
        private string projectNameField;
        
        /// <remarks/>
        public string projectId {
            get {
                return this.projectIdField;
            }
            set {
                this.projectIdField = value;
            }
        }
        
        /// <remarks/>
        public string projectName {
            get {
                return this.projectNameField;
            }
            set {
                this.projectNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/TICPivotalQAService")]
    public partial class PhaseFilter {
        
        private string projectIdField;
        
        private string phaseNameField;
        
        /// <remarks/>
        public string projectId {
            get {
                return this.projectIdField;
            }
            set {
                this.projectIdField = value;
            }
        }
        
        /// <remarks/>
        public string PhaseName {
            get {
                return this.phaseNameField;
            }
            set {
                this.phaseNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/TICPivotalQAService")]
    public partial class InspectionTypeFilter {
        
        private string projectIdField;
        
        private string inspectionTypeField;
        
        /// <remarks/>
        public string projectId {
            get {
                return this.projectIdField;
            }
            set {
                this.projectIdField = value;
            }
        }
        
        /// <remarks/>
        public string InspectionType {
            get {
                return this.inspectionTypeField;
            }
            set {
                this.inspectionTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/TICPivotalQAService")]
    public partial class ScheduledInspection {
        
        private string scheduledInspectionIdField;
        
        private string projectNameField;
        
        private string phaseNameField;
        
        private string lotRecordField;
        
        private string inspectionTypeField;
        
        private string scheduledDateField;
        
        private string projectedDateField;
        
        private string baseLineDateField;
        
        private string workflowStatusField;
        
        /// <remarks/>
        public string scheduledInspectionId {
            get {
                return this.scheduledInspectionIdField;
            }
            set {
                this.scheduledInspectionIdField = value;
            }
        }
        
        /// <remarks/>
        public string projectName {
            get {
                return this.projectNameField;
            }
            set {
                this.projectNameField = value;
            }
        }
        
        /// <remarks/>
        public string phaseName {
            get {
                return this.phaseNameField;
            }
            set {
                this.phaseNameField = value;
            }
        }
        
        /// <remarks/>
        public string lotRecord {
            get {
                return this.lotRecordField;
            }
            set {
                this.lotRecordField = value;
            }
        }
        
        /// <remarks/>
        public string inspectionType {
            get {
                return this.inspectionTypeField;
            }
            set {
                this.inspectionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string scheduledDate {
            get {
                return this.scheduledDateField;
            }
            set {
                this.scheduledDateField = value;
            }
        }
        
        /// <remarks/>
        public string projectedDate {
            get {
                return this.projectedDateField;
            }
            set {
                this.projectedDateField = value;
            }
        }
        
        /// <remarks/>
        public string baseLineDate {
            get {
                return this.baseLineDateField;
            }
            set {
                this.baseLineDateField = value;
            }
        }
        
        /// <remarks/>
        public string workflowStatus {
            get {
                return this.workflowStatusField;
            }
            set {
                this.workflowStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/TICPivotalQAService")]
    public partial class ScheduledInspectionWrapper {
        
        private FilterWrapper filterWrapperField;
        
        private ScheduledInspection[] scheduledInspectionsField;
        
        /// <remarks/>
        public FilterWrapper filterWrapper {
            get {
                return this.filterWrapperField;
            }
            set {
                this.filterWrapperField = value;
            }
        }
        
        /// <remarks/>
        public ScheduledInspection[] scheduledInspections {
            get {
                return this.scheduledInspectionsField;
            }
            set {
                this.scheduledInspectionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/TICPivotalQAService")]
    public enum ActionForInspection {
        
        /// <remarks/>
        Save,
        
        /// <remarks/>
        CreateNew,
        
        /// <remarks/>
        Delete,
        
        /// <remarks/>
        Approve,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void AuthenticateUserLoginCompletedEventHandler(object sender, AuthenticateUserLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateUserLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateUserLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InspectorObj Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InspectorObj)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetPivotalMD5MessageDigestCompletedEventHandler(object sender, GetPivotalMD5MessageDigestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPivotalMD5MessageDigestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPivotalMD5MessageDigestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetScheduledInspectionsForUserCompletedEventHandler(object sender, GetScheduledInspectionsForUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetScheduledInspectionsForUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetScheduledInspectionsForUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ScheduledInspectionWrapper Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ScheduledInspectionWrapper)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetInspectionsForUserCompletedEventHandler(object sender, GetInspectionsForUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInspectionsForUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInspectionsForUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InspectionWrapper Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InspectionWrapper)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void CreateNewInspectionCompletedEventHandler(object sender, CreateNewInspectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateNewInspectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateNewInspectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InspectionTemplate Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InspectionTemplate)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ApplyInspectionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void TestDALCompletedEventHandler(object sender, TestDALCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestDALCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestDALCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InspectorObj Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InspectorObj)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591