SELECT 
[Price], [Lot_Premium] ,[Financed_Options] ,[Concessions] ,[Elevation_Premium], [Additional_Price], QUOTE_TOTAL,
TIC_Struct_Opt_Deposit_Total,
TIC_DG_Option_Deposit_Total,
TIC_Init_Option_Deposit_Total,
TIC_Other_Deposit_Total,
TIC_Base_Price_Adj_Total,
TIC_Decorator_Adj_Total,
TIC_Structural_Adj_Total,
TIC_Closing_Cost_Adj_Total,
TIC_Design_Options_Total,
TIC_Structural_Options_Total,
Financed_Options,
TIC_Preplot_Options,
TIC_Total_Options_Deposits
FROM OPPORTUNITY WHERE OPPORTUNITY_ID = 0x00000000000000C7
SELECT TYPE, EXTENDED_PRICE, QUANTITY, PRICE, * FROM OPPORTUNITY__PRODUCT WHERE OPPORTUNITY_ID = 0x00000000000000C7


 SELECT * FROM OPPORTUNITY WHERE OPPORTUNITY_ID = 0x00000000000000C7
SELECT DIVISION_PRODUCT_ID, EXTENDED_PRICE, TYPE, PRICE, QUANTITY, * FROM OPPORTUNITY__PRODUCT WHERE TYPE = 'Structural'



-- Options Breakdown Query
SELECT COALESCE([Structural], 0) AS STRUCT_OPTION_TOTAL, [Decorator] AS DECORATOR_OPT_TOTAL
FROM
(SELECT 
	OPPORTUNITY_ID, EXTENDED_PRICE, TYPE
	FROM OPPORTUNITY__PRODUCT) OP	

PIVOT
(
	SUM(EXTENDED_PRICE)
    FOR  TYPE IN ([Structural], [Decorator])
) AS pvt
WHERE pvt.OPPORTUNITY_ID = 0x00000000000000C7



SELECT COALESCE(SUM(OP.EXTENDED_PRICE), 0) AS OPTION_TOTAL, OP.TYPE
FROM OPPORTUNITY__PRODUCT OP
WHERE OP.OPPORTUNITY_ID = 0x00000000000000C7
GROUP BY OP.TYPE


-- Option Deposits Breakdown Query
SELECT 
	COALESCE([Structural Option], 0) AS STRUCT_OPT_DEPOSIT_TOTAL,
	COALESCE([DG Option], 0) AS DECORATOR_OPT_DEPOSIT_TOTAL,
	COALESCE([Initial Deposit], 0) AS INITIAL_OPT_DEPOSIT_TOTAL,
	COALESCE([Other], 0) AS OTHER_OPT_DEPOSIT_TOTAL
FROM 
	(SELECT OPPORTUNITY_ID, AMOUNT, TYPE
	 FROM DEPOSIT) D
PIVOT
(
	SUM(AMOUNT)
    FOR TYPE IN (
					[Structural Option], 
					[DG Option],
					[Initial Deposit],
					[Other]
				)
) AS pvt
WHERE pvt.OPPORTUNITY_ID = 0x00000000000000C7


SELECT COALESCE(SUM(AMOUNT), 0) AS OPT_DEPOSIT_TOTAL, TYPE
FROM DEPOSIT
WHERE OPPORTUNITY_ID = 0x00000000000000C7
GROUP BY TYPE


-- Option Adjustments
SELECT 
	COALESCE([Base House], 0) AS BASE_PRICE_ADJ,
	COALESCE([Decorator], 0) AS DECORATOR_ADJ,
	COALESCE([Structural], 0) AS STRUCTURAL_ADJ,
	COALESCE([Closing Costs], 0) AS CLOSING_COST_ADJ

FROM 
	(SELECT OA.OPPORTUNITY_ID AS OPPORTUNITY_ID, 
	 DA.ADJUSTMENT_TYPE AS ADJUSTMENT_TYPE, OA.ADJUSTMENT_AMOUNT AS ADJUSTMENT_AMOUNT
	 FROM OPPORTUNITY_ADJUSTMENT OA
	 INNER JOIN RELEASE_ADJUSTMENT RA ON OA.RELEASE_ADJUSTMENT_ID = OA.RELEASE_ADJUSTMENT_ID
	 INNER JOIN DIVISION_ADJUSTMENT DA ON RA.DIVISION_ADJUSTMENT_ID = DA.DIVISION_ADJUSTMENT_ID) OA

PIVOT
(
	SUM(ADJUSTMENT_AMOUNT)
	FOR ADJUSTMENT_TYPE IN ([Base House], [Decorator], [Structural], [Closing Costs])
) AS pvt
WHERE pvt.OPPORTUNITY_ID = 0x00000000000000C7

SELECT COALESCE(SUM(OA.ADJUSTMENT_AMOUNT), 0) AS ADJUSTMENT_AMOUNT, DA.ADJUSTMENT_TYPE AS ADJUSTMENT_TYPE
FROM OPPORTUNITY_ADJUSTMENT OA
INNER JOIN RELEASE_ADJUSTMENT RA ON OA.RELEASE_ADJUSTMENT_ID = OA.RELEASE_ADJUSTMENT_ID
INNER JOIN DIVISION_ADJUSTMENT DA ON RA.DIVISION_ADJUSTMENT_ID = DA.DIVISION_ADJUSTMENT_ID
WHERE OA.OPPORTUNITY_ID = 0x00000000000000C7
GROUP BY DA.ADJUSTMENT_TYPE




-- PrePlot Options
SELECT COALESCE(SUM(EXTENDED_PRICE), 0) AS PREPLOT_OPTION_TOTAL
FROM OPPORTUNITY__PRODUCT OP
WHERE OP.TIC_PREPLOT_OPTION = 1
AND OP.OPPORTUNITY_ID = 0x00000000000000C7


-- Option totals without preplots
SELECT COALESCE([Structural], 0) AS STRUCT_OPTION_TOTAL, COALESCE([Decorator], 0) AS DECORATOR_OPT_TOTAL
FROM
(SELECT 
	OPPORTUNITY_ID, EXTENDED_PRICE, TYPE, TIC_PREPLOT_OPTION
	FROM OPPORTUNITY__PRODUCT) OP	

PIVOT
(
	SUM(EXTENDED_PRICE)
    FOR  TYPE IN ([Structural], [Decorator])
) AS pvt
WHERE pvt.TIC_PREPLOT_OPTION <> 1 AND
pvt.OPPORTUNITY_ID = 0x00000000000000C7


SELECT COALESCE(SUM(EXTENDED_PRICE), 0)
FROM OPPORTUNITY__PRODUCT OP
WHERE OP.TIC_PREPLOT_OPTION <> 1 AND
OP.OPPORTUNITY_ID = 0x00000000000000C7
GROUP BY TYPE

SELECT COALESCE(SUM(OP.EXTENDED_PRICE), 0) AS OPTION_TOTAL, OP.TYPE FROM OPPORTUNITY__PRODUCT OP WHERE OP.OPPORTUNITY_ID = 0x00000000000000C7 GROUP BY OP.TYPE 


