
-- GET HIP LAST RN_UPDATE FOR CONTACT
SELECT CONVERT(INT, RN_UPDATE), * FROM CONTACT 
WHERE ISNULL(TIC_INACTIVE, 0) <> 1
ORDER BY CONVERT(INT, RN_UPDATE) DESC

-- GET HIP LAST RN_UPDATE FOR LEAD_
SELECT CONVERT(INT, RN_UPDATE), * FROM LEAD_ 
WHERE ISNULL(TIC_INACTIVE, 0) <> 1
ORDER BY CONVERT(INT, RN_UPDATE) DESC

SELECT TOP 1 Last_Rn_Update_Id as HIPContactNBHDLastSyncId,
ISNULL(Last_Rn_Update_Prev_Id, 0) AS HIPContactNBHDPrevLastSyncId  FROM TIC_SYNC_RN_UPDATE
WHERE Table_Name = 'Contact_NBHD_Profile' AND Source_System = 'HIP'
-- GET LAST RN_UPDATE FOR CONTACT_NBHD_PROFILE
SELECT TOP 1 * FROM
(SELECT CONVERT(INT, CPN.RN_UPDATE) AS RN_UPDATE
FROM CONTACT_PROFILE_NEIGHBORHOOD CPN
INNER JOIN CONTACT C ON CPN.CONTACT_ID = C.CONTACT_ID
WHERE ISNULL(C.TIC_INACTIVE, 0) <> 1

UNION

SELECT CONVERT(INT, CPN.RN_UPDATE) AS RN_UPDATE
FROM CONTACT_PROFILE_NEIGHBORHOOD CPN
INNER JOIN LEAD_ L ON CPN.LEAD_ID = L.LEAD__ID
WHERE ISNULL(L.TIC_INACTIVE, 0) <> 1) AS INLINEVIEW
ORDER BY CONVERT(INT, RN_UPDATE) DESC



-- GET CONTACT SOURCE DATA
SELECT CONTACT_ID AS LINKED_ID, 'HIP' AS SOURCE_SYSTEM, FIRST_NAME, LAST_NAME, TITLE, SUFFIX, ADDRESS_1, CITY, STATE_,
ZIP, AREA_CODE, COUNTY_ID, COUNTRY, PHONE, CELL, FAX, EMAIL, M1_UNSUBSCRIBE
FROM CONTACT 
WHERE ISNULL(TIC_INACTIVE, 0) <> 1

-- GET CONTACT SOURCE DATA UPDATED DURING LAST SYNC
SELECT C.CONTACT_ID AS LINKED_ID, 'HIP' AS SOURCE_SYSTEM, C.FIRST_NAME, C.LAST_NAME, 
C.TITLE, C.SUFFIX, C.ADDRESS_1, C.CITY, C.STATE_,
C.ZIP, C.AREA_CODE, C.COUNTY_ID, C.COUNTRY, C.PHONE, C.CELL, C.FAX, C.EMAIL, C.M1_UNSUBSCRIBE, 0 AS PROCESSED
FROM CONTACT C
INNER JOIN USERS U ON C.RN_EDIT_USER = U.USERS_ID
WHERE ISNULL(C.TIC_INACTIVE, 0) <> 1
AND CONVERT(INT, C.RN_UPDATE) > ? AND CONVERT(INT, C.RN_UPDATE) < ?
AND U.LOGIN_NAME <> ?

--SEED CONTACT PROFILE NBHD
SELECT TOP 1 CONVERT(INT, CPN.RN_UPDATE)
FROM CONTACT_PROFILE_NEIGHBORHOOD CPN
INNER JOIN NEIGHBORHOOD N ON CPN.NEIGHBORHOOD_ID = N.NEIGHBORHOOD_ID
INNER JOIN DIVISION D ON N.DIVISION_ID = D.DIVISION_ID
INNER JOIN CONTACT C ON CPN.CONTACT_ID = C.CONTACT_ID
WHERE ISNULL(C.TIC_INACTIVE, 0) <> 1
ORDER BY CONVERT(INT, CPN.RN_UPDATE) DESC

-- GET CONTACT NEIGHBORHOOD PROFILE
SELECT CPN.CONTACT_PROFILE_NBHD_ID, CPN.CONTACT_ID AS CONTACT_ID, 'HIP' AS SOURCE_SYSTEM, N.NAME AS NEIGHBORHOOD_LOOKUP, 
D.NAME AS DIVISION_LOOKUP, CPN.TYPE, CPN.INACTIVE, 0 AS PROCESSED
FROM CONTACT_PROFILE_NEIGHBORHOOD CPN
INNER JOIN NEIGHBORHOOD N ON CPN.NEIGHBORHOOD_ID = N.NEIGHBORHOOD_ID
INNER JOIN DIVISION D ON N.DIVISION_ID = D.DIVISION_ID
INNER JOIN CONTACT C ON CPN.CONTACT_ID = C.CONTACT_ID
WHERE ISNULL(C.TIC_INACTIVE, 0) <> 1
AND CONVERT(INT, CPN.RN_UPDATE) > 142896

-- GET CONTACT NBHD PROFILE UPDATED DURING SYNC
SELECT CPN.CONTACT_PROFILE_NBHD_ID, CPN.CONTACT_ID, 'HIP' AS SOURCE_SYSTEM, N.NAME AS NEIGHBORHOOD_LOOKUP, 
D.NAME AS DIVISION_LOOKUP, CPN.TYPE, CPN.INACTIVE, 0 AS PROCESSED
FROM CONTACT_PROFILE_NEIGHBORHOOD CPN
INNER JOIN NEIGHBORHOOD N ON CPN.NEIGHBORHOOD_ID = N.NEIGHBORHOOD_ID
INNER JOIN DIVISION D ON N.DIVISION_ID = D.DIVISION_ID
INNER JOIN CONTACT C ON CPN.CONTACT_ID = C.CONTACT_ID
INNER JOIN USERS U ON CPN.RN_EDIT_USER = U.USERS_ID
WHERE ISNULL(C.TIC_INACTIVE, 0) <> 1
AND CONVERT(INT, CPN.RN_UPDATE) > ? AND CONVERT(INT, CPN.RN_UPDATE) < ?
AND U.LOGIN_NAME <> ?

-- GET LEAD_
SELECT L.LEAD__ID AS LINKED_ID, 'HIP' AS SOURCE_SYSTEM, L.FIRST_NAME, L.LAST_NAME, 
L.TITLE, L.SUFFIX, L.ADDRESS_1, L.CITY, L.STATE_,
L.ZIP, L.AREA_CODE, L.COUNTY_ID, L.COUNTRY, L.PHONE, L.CELL, L.FAX, L.EMAIL, L.M1_UNSUBSCRIBE, 0 AS PROCESSED 
FROM LEAD_ L
INNER JOIN USERS U ON L.RN_EDIT_USER = U.USERS_ID
WHERE ISNULL(L.TIC_INACTIVE, 0) <> 1
AND CONVERT(INT, L.RN_UPDATE) > ? AND CONVERT(INT, L.RN_UPDATE) < ?
AND U.LOGIN_NAME <> ?


-- GET CONTACT_NBHD_PROFILES FOR LEAD
SELECT CPN.CONTACT_PROFILE_NBHD_ID, CPN.LEAD_ID AS LEAD_ID, 'HIP' AS SOURCE_SYSTEM, N.NAME AS NEIGHBORHOOD_LOOKUP, 
D.NAME AS DIVISION_LOOKUP, CPN.TYPE, CPN.INACTIVE, 0 AS PROCESSED
FROM CONTACT_PROFILE_NEIGHBORHOOD CPN
INNER JOIN NEIGHBORHOOD N ON CPN.NEIGHBORHOOD_ID = N.NEIGHBORHOOD_ID
INNER JOIN DIVISION D ON N.DIVISION_ID = D.DIVISION_ID
INNER JOIN LEAD_ L ON CPN.LEAD_ID = L.LEAD__ID
WHERE ISNULL(L.TIC_INACTIVE, 0) <> 1
AND CONVERT(INT, CPN.RN_UPDATE) > ?

-- GET CONTACT_NBHD_PROFILES FOR LEAD UPDATED DURIGN SYNC
SELECT CPN.CONTACT_PROFILE_NBHD_ID, CPN.LEAD_ID AS LEAD_ID, 'HIP' AS SOURCE_SYSTEM, N.NAME AS NEIGHBORHOOD_LOOKUP, 
D.NAME AS DIVISION_LOOKUP, CPN.TYPE, CPN.INACTIVE, 0 AS PROCESSED
FROM CONTACT_PROFILE_NEIGHBORHOOD CPN
INNER JOIN NEIGHBORHOOD N ON CPN.NEIGHBORHOOD_ID = N.NEIGHBORHOOD_ID
INNER JOIN DIVISION D ON N.DIVISION_ID = D.DIVISION_ID
INNER JOIN LEAD_ L ON CPN.LEAD_ID = L.LEAD__ID
INNER JOIN USERS U ON L.RN_EDIT_USER = U.USERS_ID
WHERE ISNULL(L.TIC_INACTIVE, 0) <> 1
AND CONVERT(INT, L.RN_UPDATE) > ? AND CONVERT(INT, L.RN_UPDATE) < ?
AND U.LOGIN_NAME <> ?