--DELETE FROM TIC_OBJECTS_SAM.DBO.PRE_CONTACT
--DELETE FROM TIC_OBJECTS_SAM.DBO.PRE_CONTACT_NBHD_PROFILE
SELECT drvBATCH_ID, * FROM TIC_OBJECTS_SAM.DBO.PRE_CONTACT WHERE drvBATCH_ID = '{0D7C1767-9E1A-49A4-BA25-37756EAECDF8}'
SELECT BATCH_ID, * FROM TIC_OBJECTS_SAM.DBO.PRE_CONTACT_NBHD_PROFILE
 
WHERE BATCH_ID = '{CB321547-DDAE-4B7C-83B4-CA6E71BBAD6C}'

-- HIP Contacts to SAM
SELECT C.CONTACT_ID, 
CASE WHEN COALESCE(LK_C.FIRST_NAME, NULL) = NULL THEN C.FIRST_NAME ELSE LK_C.FIRST_NAME END AS FIRST_NAME,
CASE WHEN COALESCE(LK_C.LAST_NAME, NULL) = NULL THEN C.LAST_NAME ELSE LK_C.LAST_NAME END AS LAST_NAME,
CASE WHEN COALESCE(LK_C.EMAIL, NULL) = NULL THEN C.EMAIL ELSE LK_C.EMAIL END AS EMAIL,
CASE WHEN COALESCE(LK_C.PHONE, NULL) = NULL THEN C.PHONE ELSE LK_C.PHONE END AS PHONE,
CASE WHEN COALESCE(LK_C.CELL, NULL) = NULL THEN C.CELL ELSE LK_C.CELL END AS CELL,
CASE WHEN COALESCE(LK_C.ADDRESS_1, NULL) = NULL THEN C.ADDRESS_1 ELSE LK_C.ADDRESS_1 END AS ADDRESS_1,
CASE WHEN COALESCE(LK_C.SUFFIX, NULL) = NULL THEN C.TIC_SUFFIX ELSE LK_C.SUFFIX END AS SUFFIX,
CASE WHEN COALESCE(LK_C.CITY, NULL) = NULL THEN C.CITY ELSE LK_C.CITY END AS CITY,
CASE WHEN COALESCE(LK_C.STATE_, NULL) = NULL THEN C.STATE_ ELSE LK_C.STATE_ END AS STATE_,
CASE WHEN COALESCE(LK_C.ZIP, NULL) = NULL THEN C.ZIP ELSE LK_C.ZIP END AS ZIP,
CASE WHEN COALESCE(LK_C.COUNTRY, NULL) = NULL THEN C.COUNTRY ELSE LK_C.COUNTRY END AS COUNTRY,
CASE WHEN COALESCE(LK_C.FAX, NULL) = NULL THEN C.FAX ELSE LK_C.FAX END AS FAX,
CASE WHEN COALESCE(LK_C.M1_UNSUBSCRIBE, NULL) = NULL THEN C.M1_UNSUBSCRIBE ELSE LK_C.M1_UNSUBSCRIBE END AS M1_UNSUBSCRIBE,
'HIP' AS EXTERNAL_SOURCE_NAME,
LK_C.PROCESSED AS PROCESSED
FROM TIC_OBJECTS_SAM.DBO.PRE_CONTACT LK_C
LEFT JOIN SAM_ED.DBO.CONTACT C ON 
(C.FIRST_NAME = LK_C.FIRST_NAME AND C.LAST_NAME = LK_C.LAST_NAME)
AND (C.EMAIL = LK_C.EMAIL
	OR C.PHONE = LK_C.PHONE
	OR C.CELL = LK_C.CELL
	OR C.ADDRESS_1 = LK_C.ADDRESS_1)

WHERE ISNULL(LK_C.PROCESSED, 0) = 0


-- HIP Contact NBHD Profile
SELECT SAM_C.CONTACT_ID, TP.TIC_PROJECT_ID, TV.TIC_VILLAGE_ID,
NBHD.SOURCE_SYSTEM, NBHD.TYPE, NBHD.INACTIVE FROM TIC_OBJECTS_SAM.DBO.PRE_CONTACT_NBHD_PROFILE NBHD 
INNER JOIN IP_ED.DBO.CONTACT HIP_C ON NBHD.CONTACT_ID = HIP_C.CONTACT_ID
INNER JOIN SAM_ED.DBO.CONTACT SAM_C ON 
(HIP_C.FIRST_NAME = SAM_C.FIRST_NAME AND HIP_C.LAST_NAME = SAM_C.LAST_NAME)
AND (HIP_C.EMAIL = SAM_C.EMAIL
	OR HIP_C.PHONE = SAM_C.PHONE
	OR HIP_C.CELL = SAM_C.CELL
	OR HIP_C.ADDRESS_1 = SAM_C.ADDRESS_1)

INNER JOIN SAM_ED.DBO.TIC_PROJECT TP ON NBHD.NEIGHBORHOOD_LOOKUP = TP.TIC_PROJECT_NAME
INNER JOIN SAM_ED.DBO.TIC_VILLAGE TV ON NBHD.DIVISION_LOOKUP = TV.TIC_VILLAGE_NAME

WHERE NBHD.BATCH_ID = '{B8494246-2E38-4722-A011-8F2DE29253E5}'

WHERE ISNULL(NBHD.PROCESSED, 0) = 0



-- Query for Lead NBHD Profile
SELECT SAM_C.CONTACT_ID, TP.TIC_PROJECT_ID, TV.TIC_VILLAGE_ID,
NBHD.SOURCE_SYSTEM, NBHD.TYPE, NBHD.INACTIVE 
FROM TIC_OBJECTS_SAM.DBO.PRE_CONTACT_NBHD_PROFILE NBHD 
INNER JOIN IP_ED.DBO.LEAD_ HIP_L ON NBHD.LEAD_ID = HIP_L.LEAD__ID
INNER JOIN SAM_ED.DBO.CONTACT SAM_C ON 
(HIP_L.FIRST_NAME = SAM_C.FIRST_NAME AND HIP_L.LAST_NAME = SAM_C.LAST_NAME)
AND (HIP_L.EMAIL = SAM_C.EMAIL
	OR HIP_L.PHONE = SAM_C.PHONE
	OR HIP_L.CELL = SAM_C.CELL
	OR HIP_L.ADDRESS_1 = SAM_C.ADDRESS_1)

INNER JOIN SAM_ED.DBO.TIC_PROJECT TP ON NBHD.NEIGHBORHOOD_LOOKUP = TP.TIC_PROJECT_NAME
INNER JOIN SAM_ED.DBO.TIC_VILLAGE TV ON NBHD.DIVISION_LOOKUP = TV.TIC_VILLAGE_NAME

WHERE ISNULL(NBHD.PROCESSED, 0) = 0

-- SAM CONTACTS TO HIP
SELECT C.CONTACT_ID, 
CASE WHEN COALESCE(LK_C.FIRST_NAME, NULL) = NULL THEN C.FIRST_NAME ELSE LK_C.FIRST_NAME END AS FIRST_NAME,
CASE WHEN COALESCE(LK_C.LAST_NAME, NULL) = NULL THEN C.LAST_NAME ELSE LK_C.LAST_NAME END AS LAST_NAME,
CASE WHEN COALESCE(LK_C.EMAIL, NULL) = NULL THEN C.EMAIL ELSE LK_C.EMAIL END AS EMAIL,
CASE WHEN COALESCE(LK_C.PHONE, NULL) = NULL THEN C.PHONE ELSE LK_C.PHONE END AS PHONE,
CASE WHEN COALESCE(LK_C.CELL, NULL) = NULL THEN C.CELL ELSE LK_C.CELL END AS CELL,
CASE WHEN COALESCE(LK_C.ADDRESS_1, NULL) = NULL THEN C.ADDRESS_1 ELSE LK_C.ADDRESS_1 END AS ADDRESS_1,
CASE WHEN COALESCE(LK_C.SUFFIX, NULL) = NULL THEN C.TIC_SUFFIX ELSE LK_C.SUFFIX END AS SUFFIX,
CASE WHEN COALESCE(LK_C.CITY, NULL) = NULL THEN C.CITY ELSE LK_C.CITY END AS CITY,
CASE WHEN COALESCE(LK_C.STATE_, NULL) = NULL THEN C.STATE_ ELSE LK_C.STATE_ END AS STATE_,
CASE WHEN COALESCE(LK_C.ZIP, NULL) = NULL THEN C.ZIP ELSE LK_C.ZIP END AS ZIP,
CASE WHEN COALESCE(LK_C.COUNTRY, NULL) = NULL THEN C.COUNTRY ELSE LK_C.COUNTRY END AS COUNTRY,
CASE WHEN COALESCE(LK_C.FAX, NULL) = NULL THEN C.FAX ELSE LK_C.FAX END AS FAX,
CASE WHEN COALESCE(LK_C.M1_UNSUBSCRIBE, NULL) = NULL THEN C.M1_UNSUBSCRIBE ELSE LK_C.M1_UNSUBSCRIBE END AS M1_UNSUBSCRIBE,
'SAM' AS EXTERNAL_SOURCE_NAME,
LK_C.PROCESSED AS PROCESSED
FROM TIC_OBJECTS_SAM.DBO.PRE_CONTACT LK_C
INNER JOIN IP_ED.DBO.CONTACT C ON 
(C.FIRST_NAME = LK_C.FIRST_NAME AND C.LAST_NAME = LK_C.LAST_NAME)
AND (C.EMAIL = LK_C.EMAIL
	OR C.PHONE = LK_C.PHONE
	OR C.CELL = LK_C.CELL
	OR C.ADDRESS_1 = LK_C.ADDRESS_1)

WHERE ISNULL(LK_C.PROCESSED, 0) = 0
AND LK_C.SOURCE_SYSTEM = 'SAM'


-- SAM CONTACT TO HIP LEAD
SELECT L.LEAD__ID, 
CASE WHEN COALESCE(LK_C.FIRST_NAME, NULL) = NULL THEN L.FIRST_NAME ELSE LK_C.FIRST_NAME END AS FIRST_NAME,
CASE WHEN COALESCE(LK_C.LAST_NAME, NULL) = NULL THEN L.LAST_NAME ELSE LK_C.LAST_NAME END AS LAST_NAME,
CASE WHEN COALESCE(LK_C.EMAIL, NULL) = NULL THEN L.EMAIL ELSE LK_C.EMAIL END AS EMAIL,
CASE WHEN COALESCE(LK_C.PHONE, NULL) = NULL THEN L.PHONE ELSE LK_C.PHONE END AS PHONE,
CASE WHEN COALESCE(LK_C.CELL, NULL) = NULL THEN L.CELL ELSE LK_C.CELL END AS CELL,
CASE WHEN COALESCE(LK_C.ADDRESS_1, NULL) = NULL THEN L.ADDRESS_1 ELSE LK_C.ADDRESS_1 END AS ADDRESS_1,
CASE WHEN COALESCE(LK_C.SUFFIX, NULL) = NULL THEN L.TIC_SUFFIX ELSE LK_C.SUFFIX END AS SUFFIX,
CASE WHEN COALESCE(LK_C.CITY, NULL) = NULL THEN L.CITY ELSE LK_C.CITY END AS CITY,
CASE WHEN COALESCE(LK_C.STATE_, NULL) = NULL THEN L.STATE_ ELSE LK_C.STATE_ END AS STATE_,
CASE WHEN COALESCE(LK_C.ZIP, NULL) = NULL THEN L.ZIP ELSE LK_C.ZIP END AS ZIP,
CASE WHEN COALESCE(LK_C.COUNTRY, NULL) = NULL THEN L.COUNTRY ELSE LK_C.COUNTRY END AS COUNTRY,
CASE WHEN COALESCE(LK_C.FAX, NULL) = NULL THEN L.FAX ELSE LK_C.FAX END AS FAX,
CASE WHEN COALESCE(LK_C.M1_UNSUBSCRIBE, NULL) = NULL THEN L.M1_UNSUBSCRIBE ELSE LK_C.M1_UNSUBSCRIBE END AS M1_UNSUBSCRIBE,
'SAM' AS EXTERNAL_SOURCE_NAME,
LK_C.PROCESSED AS PROCESSED
FROM TIC_OBJECTS_SAM.DBO.PRE_CONTACT LK_C
INNER JOIN IP_ED.DBO.LEAD_ L ON 
(L.FIRST_NAME = LK_C.FIRST_NAME AND L.LAST_NAME = LK_C.LAST_NAME)
AND (L.EMAIL = LK_C.EMAIL
	OR L.PHONE = LK_C.PHONE
	OR L.CELL = LK_C.CELL
	OR L.ADDRESS_1 = LK_C.ADDRESS_1)

WHERE LK_C.SOURCE_SYSTEM = 'SAM'
AND ISNULL(LK_C.PROCESSED, 0) = 0


-- NOTHIGN FOUND SO CREATE NEW LEAD
SELECT L.LEAD__ID, 
CASE WHEN COALESCE(LK_C.FIRST_NAME, NULL) = NULL THEN L.FIRST_NAME ELSE LK_C.FIRST_NAME END AS FIRST_NAME,
CASE WHEN COALESCE(LK_C.LAST_NAME, NULL) = NULL THEN L.LAST_NAME ELSE LK_C.LAST_NAME END AS LAST_NAME,
CASE WHEN COALESCE(LK_C.EMAIL, NULL) = NULL THEN L.EMAIL ELSE LK_C.EMAIL END AS EMAIL,
CASE WHEN COALESCE(LK_C.PHONE, NULL) = NULL THEN L.PHONE ELSE LK_C.PHONE END AS PHONE,
CASE WHEN COALESCE(LK_C.CELL, NULL) = NULL THEN L.CELL ELSE LK_C.CELL END AS CELL,
CASE WHEN COALESCE(LK_C.ADDRESS_1, NULL) = NULL THEN L.ADDRESS_1 ELSE LK_C.ADDRESS_1 END AS ADDRESS_1,
CASE WHEN COALESCE(LK_C.SUFFIX, NULL) = NULL THEN L.TIC_SUFFIX ELSE LK_C.SUFFIX END AS SUFFIX,
CASE WHEN COALESCE(LK_C.CITY, NULL) = NULL THEN L.CITY ELSE LK_C.CITY END AS CITY,
CASE WHEN COALESCE(LK_C.STATE_, NULL) = NULL THEN L.STATE_ ELSE LK_C.STATE_ END AS STATE_,
CASE WHEN COALESCE(LK_C.ZIP, NULL) = NULL THEN L.ZIP ELSE LK_C.ZIP END AS ZIP,
CASE WHEN COALESCE(LK_C.COUNTRY, NULL) = NULL THEN L.COUNTRY ELSE LK_C.COUNTRY END AS COUNTRY,
CASE WHEN COALESCE(LK_C.FAX, NULL) = NULL THEN L.FAX ELSE LK_C.FAX END AS FAX,
CASE WHEN COALESCE(LK_C.M1_UNSUBSCRIBE, NULL) = NULL THEN L.M1_UNSUBSCRIBE ELSE LK_C.M1_UNSUBSCRIBE END AS M1_UNSUBSCRIBE,
'SAM' AS EXTERNAL_SOURCE_NAME,
LK_C.PROCESSED AS PROCESSED

FROM TIC_OBJECTS_SAM.DBO.PRE_CONTACT LK_C
LEFT JOIN IP_ED.DBO.LEAD_ L ON 
(L.FIRST_NAME = LK_C.FIRST_NAME AND L.LAST_NAME = LK_C.LAST_NAME)
AND (L.EMAIL = LK_C.EMAIL
	OR L.PHONE = LK_C.PHONE
	OR L.CELL = LK_C.CELL
	OR L.ADDRESS_1 = LK_C.ADDRESS_1)

WHERE LK_C.SOURCE_SYSTEM = 'SAM'
AND ISNULL(LK_C.PROCESSED, 0) = 0


-- GET TIC_CONTACT_VILLAGE_PROJECT FOR CONTACT
SELECT SAM_C.CONTACT_ID, TP.TIC_PROJECT_ID, TV.TIC_VILLAGE_ID,
NBHD.SOURCE_SYSTEM, NBHD.TYPE, NBHD.INACTIVE 
FROM TIC_OBJECTS_SAM.DBO.PRE_CONTACT_NBHD_PROFILE NBHD 
INNER JOIN IP_ED.DBO.LEAD_ HIP_L ON NBHD.LEAD_ID = HIP_L.LEAD__ID
INNER JOIN SAM_ED.DBO.CONTACT SAM_C ON 
(HIP_L.FIRST_NAME = SAM_C.FIRST_NAME AND HIP_L.LAST_NAME = SAM_C.LAST_NAME)
AND (HIP_L.EMAIL = SAM_C.EMAIL
	OR HIP_L.PHONE = SAM_C.PHONE
	OR HIP_L.CELL = SAM_C.CELL
	OR HIP_L.ADDRESS_1 = SAM_C.ADDRESS_1)

INNER JOIN SAM_ED.DBO.TIC_PROJECT TP ON NBHD.NEIGHBORHOOD_LOOKUP = TP.TIC_PROJECT_NAME
INNER JOIN SAM_ED.DBO.TIC_VILLAGE TV ON NBHD.DIVISION_LOOKUP = TV.TIC_VILLAGE_NAME

WHERE ISNULL(NBHD.PROCESSED, 0) = 0
AND NBHD.SOURCE_SYSTEM = 'SAM'



select product_id, opportunity_id, lot_status_changed_to, * 
from ip_ed..tic_int_sam_contract 
where lot_status_changed_to = 'Rollback Reserve'