
-- LEADS IN HIP WHERE CONTACT ADDRESS IN SAM IS NULL
SELECT L.TIC_HIP_INTEGRATION_ID, C.TIC_SAM_INTEGRATION_ID, U.LOGIN_NAME, C.RN_EDIT_DATE, C.RN_EDIT_USER, 
L.FIRST_NAME, L.LAST_NAME, 
L.ADDRESS_1, C.ADDRESS_1,
L.CITY, C.CITY,
L.STATE_, C.STATE_,
L.ZIP, C.ZIP,
L.PHONE, C.PHONE FROM LEAD_ L
INNER JOIN PRODMASTERED..CONTACT C ON L.TIC_HIP_INTEGRATION_ID = C.TIC_SAM_INTEGRATION_ID
INNER JOIN PRODMASTERED..USERS U ON C.RN_EDIT_USER = U.USERS_ID 
WHERE L.ADDRESS_1 IS NOT NULL AND C.ADDRESS_1 IS NULL
order by c.rn_edit_date desc

-- CONTACTS IN HIP WHERE CONTACTS ADDRESS IN SAM IS NULL
SELECT U.LOGIN_NAME, C.RN_EDIT_DATE, C.RN_EDIT_USER, 
L.FIRST_NAME, L.LAST_NAME, 
L.ADDRESS_1, C.ADDRESS_1,
L.CITY, C.CITY,
L.STATE_, C.STATE_,
L.ZIP, C.ZIP,
L.PHONE FROM CONTACT L
INNER JOIN PRODMASTERED..CONTACT C ON L.TIC_HIP_INTEGRATION_ID = C.TIC_SAM_INTEGRATION_ID
INNER JOIN PRODMASTERED..USERS U ON C.RN_EDIT_USER = U.USERS_ID 
WHERE L.ADDRESS_1 IS NOT NULL AND C.ADDRESS_1 IS NULL
order by c.rn_edit_date desc
