
--UPDATE ALL 
UPDATE CONTACT
SET TIC_SAM_INTEGRATION_ID = NEWID()
WHERE ISNULL(TIC_INACTIVE, 0) = 0

-- JOIN HIP CONTACTS WITH SAM CONTACTS
SELECT C.CONTACT_ID AS HIP_CONTACT_ID, LK_C.CONTACT_ID AS SAM_CONTACT_ID, 
LK_C.TIC_SAM_INTEGRATION_ID
FROM PRODMASTERED..CONTACT LK_C
INNER JOIN IP_ED..CONTACT C ON 
(C.FIRST_NAME = LK_C.FIRST_NAME AND C.LAST_NAME = LK_C.LAST_NAME)
AND (C.EMAIL = LK_C.EMAIL
	OR C.PHONE = LK_C.PHONE
	OR C.CELL = LK_C.CELL
	OR C.ADDRESS_1 = LK_C.ADDRESS_1)

-- JOIN HIP LEADS WITH SAM LEADS_
SELECT LK_C.CONTACT_ID AS SAM_CONTACT_ID, L.LEAD__ID AS HIP_CONTACT_ID, LK_C.TIC_SAM_INTEGRATION_ID
FROM PRODMASTERED..CONTACT LK_C
INNER JOIN IP_ED..LEAD_ L ON 
(L.FIRST_NAME = LK_C.FIRST_NAME AND L.LAST_NAME = LK_C.LAST_NAME)
AND (L.EMAIL = LK_C.EMAIL
	OR L.PHONE = LK_C.PHONE
	OR L.CELL = LK_C.CELL
	OR L.ADDRESS_1 = LK_C.ADDRESS_1)


