SELECT C.CONTACT_ID AS HIP_CONTACT_ID, LK_C.CONTACT_ID AS SAM_CONTACT_ID, 
LK_C.TIC_SAM_INTEGRATION_ID
FROM PRODMASTERED..CONTACT LK_C
INNER JOIN IP_ED..CONTACT C ON 
(C.FIRST_NAME = LK_C.FIRST_NAME AND C.LAST_NAME = LK_C.LAST_NAME)
AND (C.EMAIL = LK_C.EMAIL
	OR C.PHONE = LK_C.PHONE
	OR C.CELL = LK_C.CELL
	OR C.ADDRESS_1 = LK_C.ADDRESS_1)



SELECT LK_C.CONTACT_ID AS SAM_CONTACT_ID, L.LEAD__ID AS HIP_CONTACT_ID, LK_C.TIC_SAM_INTEGRATION_ID
FROM PRODMASTERED..CONTACT LK_C
INNER JOIN IP_ED..LEAD_ L ON 
(L.FIRST_NAME = LK_C.FIRST_NAME AND L.LAST_NAME = LK_C.LAST_NAME)
AND (L.EMAIL = LK_C.EMAIL
	OR L.PHONE = LK_C.PHONE
	OR L.CELL = LK_C.CELL
	OR L.ADDRESS_1 = LK_C.ADDRESS_1)



SELECT TIC_HIP_INTEGRATION_ID, * FROM IP_ED..CONTACT WHERE TIC_HIP_INTEGRATION_ID IS NOT NULL

SELECT COUNT(*) FROM LEAD_ WHERE RN_EDIT_DATE > '2010-10-02 16:50:00'
--
--UPDATE PRODMASTERED..CONTACT
--SET TIC_SAM_INTEGRATION_ID = NEWID()



SELECT PC.EXT_SOURCE_INTEGRATION_ID, * FROM PRODMASTERED..CONTACT C
INNER JOIN PRE_CONTACT PC ON C.CONTACT_ID = PC.LINKED_ID
WHERE DRVSOURCE_TABLE = 'Contact' AND SOURCE_SYSTEM = 'SAM'
AND C.TIC_SAM_INTEGRATION_ID IS NULL



SELECT C.CONTACT_ID, 
CASE WHEN COALESCE(LK_C.FIRST_NAME, NULL) = NULL THEN C.FIRST_NAME ELSE LK_C.FIRST_NAME END AS FIRST_NAME,
CASE WHEN COALESCE(LK_C.LAST_NAME, NULL) = NULL THEN C.LAST_NAME ELSE LK_C.LAST_NAME END AS LAST_NAME,
CASE WHEN COALESCE(LK_C.EMAIL, NULL) = NULL THEN C.EMAIL ELSE LK_C.EMAIL END AS EMAIL,
CASE WHEN COALESCE(LK_C.PHONE, NULL) = NULL THEN C.PHONE ELSE LK_C.PHONE END AS PHONE,
CASE WHEN COALESCE(LK_C.CELL, NULL) = NULL THEN C.CELL ELSE LK_C.CELL END AS CELL,
CASE WHEN COALESCE(LK_C.ADDRESS_1, NULL) = NULL THEN C.ADDRESS_1 ELSE LK_C.ADDRESS_1 END AS ADDRESS_1,
CASE WHEN COALESCE(LK_C.SUFFIX, NULL) = NULL THEN C.TIC_SUFFIX ELSE LK_C.SUFFIX END AS SUFFIX,
CASE WHEN COALESCE(LK_C.CITY, NULL) = NULL THEN C.CITY ELSE LK_C.CITY END AS CITY,
CASE WHEN COALESCE(LK_C.STATE_, NULL) = NULL THEN C.STATE_ ELSE LK_C.STATE_ END AS STATE_,
CASE WHEN COALESCE(LK_C.ZIP, NULL) = NULL THEN C.ZIP ELSE LK_C.ZIP END AS ZIP,
CASE WHEN COALESCE(LK_C.COUNTRY, NULL) = NULL THEN C.COUNTRY ELSE LK_C.COUNTRY END AS COUNTRY,
CASE WHEN COALESCE(LK_C.FAX, NULL) = NULL THEN C.FAX ELSE LK_C.FAX END AS FAX,
CASE WHEN COALESCE(LK_C.M1_UNSUBSCRIBE, NULL) = NULL THEN C.M1_UNSUBSCRIBE ELSE LK_C.M1_UNSUBSCRIBE END AS M1_UNSUBSCRIBE,
'HIP' AS EXTERNAL_SOURCE_NAME,
LK_C.PROCESSED AS PROCESSED,
M.MARKETING_PROJECT_ID AS MARKETING_PROJECT_ID,
LK_C.EXT_SOURCE_INTEGRATION_ID, LK_C.drvSOURCE_TABLE, LK_C.SOURCE_SYSTEM 
FROM TIC_OBJECTS..PRE_CONTACT LK_C
LEFT JOIN ProdMasterED..CONTACT C ON 
LK_C.EXT_SOURCE_INTEGRATION_ID = C.TIC_SAM_Integration_Id
LEFT JOIN ProdMasterED..MARKETING_PROJECT M ON LK_C.MARKETING_PROJECT_NAME = M.MARKETING_PROJECT_NAME


WHERE ISNULL(LK_C.PROCESSED, 0) = 0
AND LK_C.SOURCE_SYSTEM = 'HIP'







select * from pre_contact




SELECT NBHD.CONTACT_PROFILE_NBHD_ID, HIP_C.CONTACT_ID AS CONTACT_ID,
D.DIVISION_ID, N.NEIGHBORHOOD_ID, NBHD.TYPE, NBHD.INACTIVE
FROM TIC_OBJECTS..PRE_CONTACT_NBHD_PROFILE NBHD
INNER JOIN ProdMasterED..CONTACT SAM_C ON NBHD.CONTACT_ID = SAM_C.CONTACT_ID
INNER JOIN IP_ED..CONTACT HIP_C ON 
(SAM_C.FIRST_NAME = HIP_C.FIRST_NAME AND SAM_C.LAST_NAME = HIP_C.LAST_NAME)
AND (SAM_C.EMAIL = HIP_C.EMAIL
	OR SAM_C.PHONE = HIP_C.PHONE
	OR SAM_C.CELL = HIP_C.CELL
	OR SAM_C.ADDRESS_1 = HIP_C.ADDRESS_1)
INNER JOIN IP_ED..DIVISION D ON NBHD.DIVISION_LOOKUP = D.NAME
INNER JOIN IP_ED..NEIGHBORHOOD N ON NBHD.NEIGHBORHOOD_LOOKUP = N.NAME
WHERE ISNULL(NBHD.PROCESSED, 0) = 0
AND ISNULL(SAM_C.TIC_INACTIVE, 0) <> 1
AND NBHD.SOURCE_SYSTEM = 'SAM'
AND SAM_C.contact_id Not in (
--anyone hooked to sale on custom lot
Select distinct Contact_Id
From Contact c 
Join TIC_sale s on c.contact_Id=s.TIC_Buyer_1_Contact_Id or c.contact_id=TIC_Buyer_2_Contact_Id
Join TIC_Project p on p.tic_project_id=s.TIC_project_id
where TIC_Default_Lot_Type ='Custom Lot'
And Isnull(S.TIC_Deleted,0)=0

Union
--anyone hooked to current custom lot compliance
Select Distinct Contact_id
From Contact c
join TIC_Custom_lot_Compliance clc on c.contact_id=clc.tic_Owner_1_Contact_Id or c.contact_id=clc.tic_Owner_2_Contact_Id

Union
--anyone who previous owned the clc lot
Select Distinct Contact_id
From Contact c
join TIC_lot_Owner_History loh on c.contact_id=loh.tic_Owner_1_Contact_Id or c.contact_id=loh.tic_Owner_2_Contact_Id

)



SELECT * FROM PRE_CONTACT_NBHD_PROFILE


select newid() from ip_ed..contact



SELECT LK_C.LINKED_ID AS UPDATE_KEY, C.CONTACT_ID, 
CASE WHEN COALESCE(LK_C.FIRST_NAME, NULL) = NULL THEN C.FIRST_NAME ELSE LK_C.FIRST_NAME END AS FIRST_NAME,
CASE WHEN COALESCE(LK_C.LAST_NAME, NULL) = NULL THEN C.LAST_NAME ELSE LK_C.LAST_NAME END AS LAST_NAME,
CASE WHEN COALESCE(LK_C.EMAIL, NULL) = NULL THEN C.EMAIL ELSE LK_C.EMAIL END AS EMAIL,
CASE WHEN COALESCE(LK_C.PHONE, NULL) = NULL THEN C.PHONE ELSE LK_C.PHONE END AS PHONE,
CASE WHEN COALESCE(LK_C.CELL, NULL) = NULL THEN C.CELL ELSE LK_C.CELL END AS CELL,
CASE WHEN COALESCE(LK_C.ADDRESS_1, NULL) = NULL THEN C.ADDRESS_1 ELSE LK_C.ADDRESS_1 END AS ADDRESS_1,
CASE WHEN COALESCE(LK_C.SUFFIX, NULL) = NULL THEN C.TIC_SUFFIX ELSE LK_C.SUFFIX END AS SUFFIX,
CASE WHEN COALESCE(LK_C.CITY, NULL) = NULL THEN C.CITY ELSE LK_C.CITY END AS CITY,
CASE WHEN COALESCE(LK_C.STATE_, NULL) = NULL THEN C.STATE_ ELSE LK_C.STATE_ END AS STATE_,
CASE WHEN COALESCE(LK_C.ZIP, NULL) = NULL THEN C.ZIP ELSE LK_C.ZIP END AS ZIP,
CASE WHEN COALESCE(LK_C.COUNTRY, NULL) = NULL THEN C.COUNTRY ELSE LK_C.COUNTRY END AS COUNTRY,
CASE WHEN COALESCE(LK_C.FAX, NULL) = NULL THEN C.FAX ELSE LK_C.FAX END AS FAX,
CASE WHEN COALESCE(LK_C.M1_UNSUBSCRIBE, NULL) = NULL THEN C.M1_UNSUBSCRIBE ELSE LK_C.M1_UNSUBSCRIBE END AS M1_UNSUBSCRIBE,
'SAM' AS EXTERNAL_SOURCE_NAME,
LK_C.PROCESSED AS PROCESSED,
M.MARKETING_PROJECT_ID AS MARKETING_PROJECT_ID, LK_C.EXT_SOURCE_INTEGRATION_ID 
FROM TIC_OBJECTS..PRE_CONTACT LK_C
INNER JOIN IP_ED..CONTACT C ON 
LK_C.EXT_SOURCE_INTEGRATION_ID = C.TIC_HIP_Integration_Id



LEFT JOIN IP_ED..MARKETING_PROJECT M ON LK_C.MARKETING_PROJECT_NAME = M.MARKETING_PROJECT_NAME
WHERE ISNULL(LK_C.PROCESSED, 0) = 0
AND LK_C.SOURCE_SYSTEM = 'SAM' AND LK_C.drvSOURCE_TABLE = 'Contact'







SELECT C.CONTACT_ID AS HIP_CONTACT_ID, LK_C.CONTACT_ID AS SAM_CONTACT_ID, 
LK_C.TIC_SAM_INTEGRATION_ID

FROM PRODMASTERED..CONTACT LK_C
INNER JOIN IP_ED..CONTACT C ON 
(C.FIRST_NAME = LK_C.FIRST_NAME AND C.LAST_NAME = LK_C.LAST_NAME)
AND (C.EMAIL = LK_C.EMAIL
	OR C.PHONE = LK_C.PHONE
	OR C.CELL = LK_C.CELL
	OR C.ADDRESS_1 = LK_C.ADDRESS_1)


SELECT * FROM PRE_CONTACT