SELECT PROCESS_FAILURE_REASON, STATUS, NEIGHBORHOOD, TOTAL_QUANTITY, LOT_NUMBER, UNIT, TRACT, PLAN_CODE, PHASE, UNIT_COST, TOTAL_PRICE, UNIT_PRICE,
OPTION_NUMBER, PRODUCT_NAME, * FROM TIC_INT_OPTION_SELECTIONS
--DELETE FROM TIC_INT_OPTION_SELECTIONS


-- ALL LOTS FOR CAPISTRANO
SELECT N.EXTERNAL_SOURCE_COMMUNITY_ID, BUSINESS_UNIT_LOT_NUMBER, LOT_NUMBER, 
UNIT, TRACT, * FROM PRODUCT P
INNER JOIN NEIGHBORHOOD N ON P.NEIGHBORHOOD_ID = P.NEIGHBORHOOD_ID
WHERE N.EXTERNAL_SOURCE_COMMUNITY_ID = '10'
--
--update product
--set business_unit_lot_number = '10-2-38-17357'
--where product_id = 0x000000000000009A

-- GET LOT TO TEST
SELECT P.LOT_STATUS, P.PRODUCT_ID, N.EXTERNAL_SOURCE_COMMUNITY_ID, PH.PHASE_NAME, NP.RN_DESCRIPTOR, NP.CODE_, 
BUSINESS_UNIT_LOT_NUMBER, LOT_NUMBER, UNIT, TRACT, * FROM PRODUCT P
INNER JOIN NEIGHBORHOOD N ON P.NEIGHBORHOOD_ID = N.NEIGHBORHOOD_ID
INNER JOIN NBHD_PHASE PH ON P.NBHD_PHASE_ID = PH.NBHD_PHASE_ID
INNER JOIN NBHDP_PRODUCT NP ON P.PLAN_ID = NP.NBHDP_PRODUCT_ID 

--EXISTING NEIGHBORHOOD OPTION
SELECT NP.TYPE, NP.NBHDP_PRODUCT_ID, NP.PLAN_WILDCARD, NP.RELEASE_WILDCARD, NP.EXTERNAL_SOURCE_ID, NP.WC_Region_Id, 
NP.WC_Corporate, NP.WC_Division_Id, NP.WC_Neighborhood_Id, np.WC_Release_Id, NP.CODE_ FROM NBHDP_PRODUCT NP
WHERE NP.RN_CREATE_DATE > '2010-08-16 00:00:00'
AND NP.TYPE = 'Decorator'

UPDATE NBHDP_PRODUCT
SET WC_CORPORATE = 0
WHERE NBHDP_PRODUCT_ID = 0x0000000000000135

--EXISTING NEIGHBORHOOD PLAN
SELECT NP.NBHDP_PRODUCT_ID, NP.PLAN_WILDCARD, NP.EXTERNAL_SOURCE_ID, * FROM NBHDP_PRODUCT NP
WHERE NP.NBHDP_PRODUCT_ID = 0x00000000000000A1

SELECT * FROM DIVISION_PRODUCT WHERE DIVISION_PRODUCT_ID = 0x0000000000000153

UPDATE NBHDP_PRODUCT
SET PLAN_WILDCARD = 1
WHERE NBHDP_PRODUCT_ID = 0x0000000000000135

SELECT CODE_, * FROM CONFIGURATION_TYPE

SELECT EXTERNAL_SOURCE_NAME, * FROM OPPORTUNITY WHERE RN_CREATE_DATE > '2010-08-23 00:00:00'
SELECT TIC_PRICE_MISMATCH, * FROM OPPORTUNITY__PRODUCT WHERE RN_CREATE_DATE > '2010-08-23 00:00:00'
SELECT * FROM CHANGE_ORDER WHERE RN_CREATE_DATE > '2010-08-23 00:00:00'

SELECT SALES_DATE, * FROM PRODUCT WHERE PRODUCT_ID = 0x0000000000000099
UPDATE PRODUCT
SET LOT_STATUS = 'Available'
WHERE PRODUCT_ID = 0x0000000000000099

DELETE FROM OPPORTUNITY__PRODUCT WHERE OPPORTUNITY_ID = 0x0000000000000167
DELETE FROM OPPORTUNITY WHERE OPPORTUNITY_ID = 0x0000000000000167

update region
set external_source_id = '001'
