SELECT EXTERNAL_SOURCE_ID FROM REGION
SELECT EXTERNAL_SOURCE_COMMUNITY_ID, * FROM NEIGHBORHOOD

-- Option Master Mappings
SELECT Rn_Create_Date, Product_Name, Category_Id, Code_, TIC_Code, Type, Region_Id, Style_Number,
Manufacturer, Units_Of_Measure,TIC_Model, Removal_Date, Comments, External_Source_Id,
Available_Date,* FROM DIVISION_PRODUCT WHERE TYPE = 'Decorator'

-- Option Configuration Mappings
SELECT NBHDP_PRODUCT_ID, NP.TYPE, C.RN_DESCRIPTOR, np.rn_descriptor, External_Source_Id, NP.Code_, Neighborhood_Id, Plan_Id, Cost_Price, TIC_Cost, Option_Available_To, Nbhd_Phase_Id,
Removal_Date, Region_Id, NP.Division_Id, Default_Product, Next_Cost_Price, Price_Change_Date,
Next_Margin, Division_Product_Id, Available_date
FROM NBHDP_PRODUCT NP 
INNER JOIN CONFIGURATION_TYPE C ON NP.CATEGORY_ID = C.CONFIGURATION_TYPE_ID WHERE TYPE = 'Other'
order by plan_id asc

SELECT * FROM DIVISION_PRODUCT WHERE DIVISION_PRODUCT_ID = 0x000000000000014F
SELECT PLAN_ID, * FROM NBHDP_PRODUCT WHERE DIVISION_PRODUCT_ID = 0x000000000000014F


SELECT * FROM NBHDP_PRODUCT WHERE NBHDP_PRODUCT_ID = 0x0000000000000016

SELECT * FROM DIVISION_PRODUCT WHERE DIVISION_PRODUCT_ID = 0x0000000000000017
SELECT PLAN_ID, * FROM NBHDP_PRODUCT WHERE DIVISION_PRODUCT_ID = 0x0000000000000017
--
Cannot find the NBHDP_Product from the Plan (0x0000000000000016) and Division_Product (0x00000000000000E5) .
Cannot find the NBHDP_Product from the Plan (0x0000000000000016) and Division_Product (0x000000000000014F) .



SELECT CODE_, * FROM NBHDP_PRODUCT WHERE TYPE = 'Elevation'
SELECT EXTERNAL_SOURCE_ID, RELEASE_WILDCARD, * FROM NBHDP_PRODUCT WHERE TYPE = 'Decorator'
SELECT BUSINESS_UNIT_LOT_NUMBER, * FROM PRODUCT
SELECT STATUS, PROCESS_FAILURE_REASON, * FROM TIC_INT_OPTION_SELECTIONS 

